"""Export the deterministic portfolio_health rows as a Databricks AI/BI dashboard seed.

Runs MAX over the synthetic fleet and writes, next to this file:
  - pm_health_seed.csv          row-level, for inspection / COPY INTO
  - pm_health_seed_values.sql   a CREATE OR REPLACE TABLE ... FROM VALUES block

The seed lets the AI/BI (Lakeview) dashboard show real, governed rows immediately (synthetic-first).
In production, replace the seeded table with the v_* view template in pm_health_dashboard_setup.sql;
the dashboard queries the same table name either way, so nothing downstream changes.

Run from anywhere:  python dashboards/export_pm_health_seed.py
Target table override:  set MAX_PM_HEALTH_TABLE (default supplychain.max_agent.pm_health)
"""

from __future__ import annotations

import csv
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from max_agent.orchestrator import MaxAgent  # noqa: E402

COLUMNS = [
    "equipment_id", "asset_class", "criticality", "label", "gate_status",
    "data_readiness", "do_not_optimize", "next_action", "reason", "provenance",
]


def collect_rows():
    agent = MaxAgent()
    health = agent.portfolio_health()
    out = []
    for r in health.get("rows", []):
        out.append({
            "equipment_id": r.get("equipment_id"),
            "asset_class": r.get("asset_class"),
            "criticality": None if r.get("criticality") is None else str(r.get("criticality")),
            "label": r.get("label"),
            "gate_status": r.get("gate_status"),
            "data_readiness": r.get("data_readiness"),
            "do_not_optimize": bool(r.get("do_not_optimize")),
            "next_action": r.get("next_action") or "-",
            "reason": r.get("gate_reason") or r.get("gate_review_trigger") or "-",
            "provenance": r.get("provenance") or "SYNTHETIC",
        })
    return out


def _sql_literal(v):
    if isinstance(v, bool):
        return "true" if v else "false"
    if v is None:
        return "NULL"
    return "'" + str(v).replace("'", "''") + "'"


def main():
    data = collect_rows()
    with open(os.path.join(HERE, "pm_health_seed.csv"), "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=COLUMNS)
        w.writeheader()
        for r in data:
            w.writerow(r)

    table = os.environ.get("MAX_PM_HEALTH_TABLE", "supplychain.max_agent.pm_health")
    values = ",\n".join("  (" + ", ".join(_sql_literal(r[c]) for c in COLUMNS) + ")" for r in data)
    sql = (
        "-- Generated by dashboards/export_pm_health_seed.py from the synthetic fleet (portfolio_health()).\n"
        "-- Synthetic-first seed so the AI/BI dashboard shows governed rows immediately.\n"
        "-- In production, swap this for the v_* view template in pm_health_dashboard_setup.sql.\n"
        f"CREATE OR REPLACE TABLE {table} AS\n"
        "SELECT * FROM VALUES\n"
        f"{values}\n"
        f"AS t({', '.join(COLUMNS)});\n"
    )
    with open(os.path.join(HERE, "pm_health_seed_values.sql"), "w", encoding="utf-8") as f:
        f.write(sql)

    print(f"rows: {len(data)}")
    print(sql)


if __name__ == "__main__":
    main()
